#     _   _                  _                 _ 
#    | | | |                | |               | |
#    | |_| |_   _ _ __  _ __| | __ _ _ __   __| |
#    |  _  | | | | '_ \| '__| |/ _` | '_ \ / _` |
#    | | | | |_| | |_) | |  | | (_| | | | | (_| |
#    \_| |_/\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#            __/ | |                             
#           |___/|_|                             


#══════════════════ Sources ════════════════╗
source = ~/.config/hypr/colors.conf        #║
source = ~/.config/hypr/autostart.conf     #║
source = ~/.config/hypr/decoration.conf    #║
source = ~/.config/hypr/keybindings.conf   #║
source = ~/.config/hypr/animations.conf    #║
source = ~/.config/hypr/rules.conf         #║
source = ~/.config/hypr/monitors.conf      #║
source = ~/.config/hypr/permissions.conf   #║
source = ~/.config/hypr/layouts.conf       #║
source = ~/.config/hypr/input.conf         #║
source = ~/.config/hypr/gestures.conf      #║
source = ~/.config/hypr/misc.conf          #║
source = ~/.config/hypr/group.conf         #║
#══════════════════ Sources ════════════════╝
