hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpolkitagent")
    hl.exec_cmd("waybar")
    hl.exec_cmd("openrgb --profile ~/.config/OpenRGB/green.orp")
    -- hl.exec_cmd("awww-daemon")
    hl.exec_cmd("mpvpaper -o \"--loop --video-aspect-override=no --panscan=1.0\" DP-1 /home/chris/Videos/wallpaper/Terrarium.mp4")
    hl.exec_cmd("mpvpaper -o \"--loop --video-aspect-override=no --panscan=1.0\" DP-2 /home/chris/Videos/wallpaper/Terrarium.mp4")
    -- hl.exec_cmd("swaync")
    -- hl.exec_cmd("solaar --window hide")
end)
