-- Hyprland Colors - Generated by Matugen

primary = "rgba(c2cd7cff)"
on_primary = "rgba(2d3400ff)"
primary_container = "rgba(424b06ff)"
on_primary_container = "rgba(deea96ff)"

secondary = "rgba(c6c9a7ff)"
on_secondary = "rgba(2f321aff)"
secondary_container = "rgba(45492fff)"
on_secondary_container = "rgba(e2e5c2ff)"

tertiary = "rgba(a2d0c2ff)"
on_tertiary = "rgba(06372eff)"
tertiary_container = "rgba(224e44ff)"
on_tertiary_container = "rgba(bdecdeff)"

error = "rgba(ffb4abff)"
on_error = "rgba(690005ff)"
error_container = "rgba(93000aff)"
on_error_container = "rgba(ffdad6ff)"

background = "rgba(13140dff)"
on_background = "rgba(e4e3d6ff)"

surface = "rgba(13140dff)"
on_surface = "rgba(e4e3d6ff)"
surface_variant = "rgba(47483bff)"
on_surface_variant = "rgba(c8c7b7ff)"

outline = "rgba(919283ff)"
outline_variant = "rgba(47483bff)"

shadow = "rgba(000000ff)"
surface_dim = "rgba(13140dff)"
surface_bright = "rgba(393a31ff)"
surface_container = "rgba(1f2018ff)"
surface_container_high = "rgba(2a2b22ff)"
surface_container_highest = "rgba(35352dff)"
surface_container_low = "rgba(1b1c15ff)"
surface_container_lowest = "rgba(0e0f08ff)"
