hl.config({
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        disable_scale_notification = false,
        col = {
            splash = 0xffffffff,
        },
        font_family = "JetBrainsMono Nerd Font",
        splash_font_family = "",
        force_default_wallpaper = 0,
        vrr = 0,
        mouse_move_enables_dpms = false,
        key_press_enables_dpms = false,
        name_vk_after_proc = true,
        always_follow_on_dnd = true,
        layers_hog_keyboard_focus = true,
        animate_manual_resizes = false,
        animate_mouse_windowdragging = false,
        disable_autoreload = false,
        enable_swallow = false,
        swallow_regex = "Empty",
        swallow_exception_regex = "Empty",
        focus_on_activate = false,
        mouse_move_focuses_monitor = true,
        allow_session_lock_restore = false,
        session_lock_xray = false,
        background_color = 0x111111,
        close_special_on_empty = true,
        on_focus_under_fullscreen = 2,
        exit_window_retains_fullscreen = false,
        initial_workspace_tracking = 1,
        middle_click_paste = false,
        render_unfocused_fps = 15,
        disable_xdg_env_checks = false,
        lockdead_screen_delay = 1000,
        enable_anr_dialog = true,
        anr_missed_pings = 5,
        size_limits_tiled = false,
        disable_watchdog_warning = false,
    },
})
