#     _   _                  _                 _      ___        _            _             _   
#    | | | |                | |               | |    / _ \      | |          | |           | |  
#    | |_| |_   _ _ __  _ __| | __ _ _ __   __| |   / /_\ \_   _| |_ ___  ___| |_ __ _ _ __| |_ 
#    |  _  | | | | '_ \| '__| |/ _` | '_ \ / _` |   |  _  | | | | __/ _ \/ __| __/ _` | '__| __|
#    | | | | |_| | |_) | |  | | (_| | | | | (_| |   | | | | |_| | || (_) \__ \ || (_| | |  | |_ 
#    \_| |_/\__, | .__/|_|  |_|\__,_|_| |_|\__,_|   \_| |_/\__,_|\__\___/|___/\__\__,_|_|   \__|
#            __/ | |                                                                            
#           |___/|_|                                                                            




#════════════════════════════ Animations ═══════════════════════════╗
exec-once = hyprpolkitagent                                        #║
exec-once = waybar                                                 #║
exec-once = openrgb --profile ~/.config/OpenRGB/evergreen.orp      #║
exec-once = swww-daemon                                            #║
exec-once = swaync                                                 #║
exec-once = eww daemon                                             #║
exec-once = solaar --window hide                                   #║
#════════════════════════════ Animations ═══════════════════════════╝