# ---------------
# 4. AUTOSTART
# ---------------
# Autostart necessary processes (like notifications daemons, status bars, etc.)

exec-once = hyprpolkitagent
exec-once = waybar -c ~/.config/waybar/config-dp1.jsonc &
exec-once = waybar -c ~/.config/waybar/config-dp2.jsonc &
exec-once = openrgb --profile ~/.config/OpenRGB/Blue\ \(samurai\ wallpaper\).orp
exec-once = swww-daemon
exec-once = swaync
exec-once = eww daemon