#     _   _                  _                 _    ______      _           
#    | | | |                | |               | |   | ___ \    | |          
#    | |_| |_   _ _ __  _ __| | __ _ _ __   __| |   | |_/ /   _| | ___  ___ 
#    |  _  | | | | '_ \| '__| |/ _` | '_ \ / _` |   |    / | | | |/ _ \/ __|
#    | | | | |_| | |_) | |  | | (_| | | | | (_| |   | |\ \ |_| | |  __/\__ \
#    \_| |_/\__, | .__/|_|  |_|\__,_|_| |_|\__,_|   \_| \_\__,_|_|\___||___/
#            __/ | |                                                        
#           |___/|_|                                                        


#╔══════════════════════════════════════╗
#║           WORKSPACE RULES            ║
#╚══════════════════════════════════════╝
#https://wiki.hypr.land/Configuring/Workspace-Rules/

# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#     name = no-gaps-wtv1
#     match:float = false
#     match:workspace = w[tv1]
#
#     border_size = 0
#     rounding = 0
# }
#
# windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
# }

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}




$720 = 1280 720

windowrule = match:class thunar, float true
windowrule = match:class thunar, size $720
windowrule = match:class thunar, center 1

windowrule = match:class LRCGET, float true
windowrule = match:class LRCGET, size $720
windowrule = match:class LRCGET, center 1

windowrule = match:title rmpc, float true
windowrule = match:title rmpc, size 1320 885
windowrule = match:title rmpc, center 1

windowrule = match:title clock, float true
windowrule = match:title clock, size 600 300
windowrule = match:title clock, center 1

windowrule = match:title kittyfloat, float true
windowrule = match:title kittyfloat, size 1280 825
windowrule = match:title kittyfloat, center 1

windowrule = match:title superfile, float true
windowrule = match:title superfile, size 1280 825
windowrule = match:title superfile, center 1

windowrule = match:title vim, float true
windowrule = match:title vim, size 1280 825
windowrule = match:title vim, center 1

windowrule = match:title nvim, float true
windowrule = match:title nvim, size 1280 825
windowrule = match:title nvim, center 1

windowrule = match:title OpenRGB, float true
windowrule = match:title OpenRGB, size $720
windowrule = match:title OpenRGB, center 1




windowrule = match:title calander, float true
windowrule = match:title calander, size 1280 825
windowrule = match:title calander, center 1

windowrule = match:title wiremix, float true
windowrule = match:title wiremix, size 940 360
windowrule = match:title wiremix, move 820 48

windowrule = match:title impala, float true
windowrule = match:title impala, size 774 1381
windowrule = match:title impala, move 1776 48

windowrule = match:title bluetui, float true
windowrule = match:title bluetui, size 774 1381
windowrule = match:title bluetui, move 1776 48
