# -----------------
# 7. LOOK AND FEEL                  Refer to https://wiki.hypr.land/Configuring/Variables/
# -----------------                 https://wiki.hypr.land/Configuring/Variables/#general

general {

    # -------------------
    # 7.1 Gaps | Border
    # -------------------
    gaps_in = 4
    gaps_out = 10
    border_size = 1


    # --------------------
    # 7.2 Border Colors             https://wiki.hypr.land/Configuring/Variables/#variable-types
    # --------------------
    col.active_border = rgba(FFFFFFaa)
    col.inactive_border = rgba(00000000)


    # --------------------------------------------------------
    # 7.3 Resizing by clicking and dragging on borders
    # --------------------------------------------------------
    resize_on_border = true


    # ------------------
    # 7.4 keine ahnung              https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    # ------------------
    allow_tearing = false

    layout = dwindle
}
